version: '3'
services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
  app:
    build: ./
    command: python manage.py runserver 0:3000 # 0.0.0.0:3000 の意
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes: 
      - ./:/application/